### ISSUE TITLE
How to only show percentages using crosstable?

### ISSUE THREAD

**Issue by kathrynagnas** [DanChaltiel/crosstable#13]
Hi there, 

I really like the usability of this package, but I've been having issues with figuring out how to show only percentages on my output from the instructions. For example, my output would come out like the photo below, but I only want the percentages and not the Count + percentages.  I have my code and an example of my output attached below. Thank you!

df1 <- crosstable(ce_c, c(msgc1_emotion,msgc2_emotion,msgc3_emotion,msgc4_emotion,msgc5_emotion), by=condition,showNA="no", percent_digits=0)  %>%
  as_flextable(keep_id=FALSE)
df1

<img width="282" alt="Screen Shot 2022-05-05 at 10 43 57 PM" src="https://user-images.githubusercontent.com/88634613/167058311-9a2ff5b1-4d62-41d5-84ce-74417daf8089.png">

**Comment by DanChaltiel** [comment]
Hi Kathryn,

I'm pleased that you like the package.

Although, for questions like this, please use Stackoverflow with tags `r` and `crosstable` as they are not really issues, bound to change the source code.

Here, you should try `percent_pattern="{p_col}"` (or `p_row`, as you like).
However, please note that there is a minor chance that this might change in the future to `percent_pattern="{p_col}%"`, as mentioned in another issue.

**Comment by kathrynagnas** [comment]
Hi Dan, 

Got it, thank you! I actually tried doing that a while back, but the output still doesn't come out as only percentages.

message1 <- crosstable(ce_control, c(msgctrl1_emotion,msgctrl2_emotion,msgctrl3_emotion,msgctrl4_emotion,msgctrl5_emotion), by=condition,showNA="no", percent_digits=0, percent_pattern="{p_col}") %>%
  as_flextable(keep_id=FALSE)
message1

<img width="643" alt="Screen Shot 2022-05-06 at 5 51 55 AM" src="https://user-images.githubusercontent.com/88634613/167109208-529003f7-7972-4122-b370-8c0d354e5a23.png">

**Comment by DanChaltiel** [comment]
Oh, this is surprising, as it works just fine on my computer:
``` r
library(crosstable)
crosstable(mtcars2, c(am), by=vs, percent_digits=0, percent_pattern="{p_col}")
#> # A tibble: 2 x 5
#>   .id   label        variable straight vshaped
#>   <chr> <chr>        <chr>    <chr>    <chr>  
#> 1 am    Transmission auto     50%      67%    
#> 2 am    Transmission manual   50%      33%
```

<sup>Created on 2022-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

What version of crosstable are you using? Could you share the output of `sessionInfo()`?

PS: using `reprex::reprex()` is the best way to share R code, as it ensure you can run the code on any machine

**Comment by DanChaltiel** [comment]
OK so you seem up to date, this is weirder and weirder.
Did you try the code I shared just above? Does it give you the right output for percentages?

If it does, I will need a reproducible example with an extract of your own dataset, so I can find what is wrong in the package's code.
Please use `dput()` to share the dataset and try to keep it as short as you can. I have to be able to just copy-paste your code and run it on my computer without needing anything else, otherwise debugging will not be possible. I advise you to use `reprex::reprex()` to generate the output as it will check that; you can read more on https://reprex.tidyverse.org/.

**Comment by kathrynagnas** [comment]
I tried your example it works, but whenever I use my own personal datasets it still only shows the count and the percentages. 

I'm a bit new with reprex and had some issues with sharing it, so at the moment I was able to take out a small portion of my sample and saved it as a CSV file. I apologize for the inconvenience this may cost and I appreciate your help!

`ce_control <- test %>%
  filter(condition=="control")

message1 <- crosstable(ce_control, c(msgctrl1_emotion,msgctrl2_emotion,msgctrl3_emotion,msgctrl4_emotion,msgctrl5_emotion), by=condition, showNA="no", percent_pattern="{p_col}", percent_digits=0) %>%
  as_flextable(keep_id=FALSE)
message1`

**Comment by kathrynagnas** [comment]
I tried your example it works, but whenever I use my own personal datasets it still only shows the count and the percentages. 

I'm a bit new with reprex and had some issues with sharing it, so at the moment I was able to take out a small portion of my sample and saved it as a xlsx file for the time being (I will keeping trying to save it using reprex). I apologize for the inconvenience this may cost and I appreciate your help! 

`test <- test %>%
  filter(condition=="control")

check <- crosstable(test, c(msgctrl1_emotion,msgctrl2_emotion,msgctrl3_emotion,msgctrl4_emotion,msgctrl5_emotion), by=condition, showNA="no", percent_pattern="{p_col}", percent_digits=0) %>%
  as_flextable(keep_id=FALSE)
check
`

[test.xlsx](https://github.com/DanChaltiel/crosstable/files/8640248/test.xlsx)

**Comment by DanChaltiel** [comment]
There is indeed a bug in the package, so you were totally right to post it here as an issue, my bad!

It seems to happen when`by=...` having only one possible value.

Here is the reprex:
``` r
library(crosstable)
test = structure(list(msgctrl1_emotion = c("no emotion", NA, "no emotion", "determined", "annoyed"), condition = c("control", "control", "control", "control", "control")), row.names = c(NA, -5L), class = c("tbl_df", "tbl", "data.frame"))
crosstable(test, c(msgctrl1_emotion), by=condition, percent_pattern="{p_col}", percent_digits=0)
#> # A tibble: 4 x 4
#>   .id              label            variable   control
#>   <chr>            <chr>            <chr>      <chr>  
#> 1 msgctrl1_emotion msgctrl1_emotion annoyed    1 (25%)
#> 2 msgctrl1_emotion msgctrl1_emotion determined 1 (25%)
#> 3 msgctrl1_emotion msgctrl1_emotion no emotion 2 (50%)
#> 4 msgctrl1_emotion msgctrl1_emotion NA         1
crosstable(test, c(msgctrl1_emotion), percent_pattern="{p_col}", percent_digits=0)
#> # A tibble: 4 x 4
#>   .id              label            variable   value
#>   <chr>            <chr>            <chr>      <chr>
#> 1 msgctrl1_emotion msgctrl1_emotion annoyed    25%  
#> 2 msgctrl1_emotion msgctrl1_emotion determined 25%  
#> 3 msgctrl1_emotion msgctrl1_emotion no emotion 50%  
#> 4 msgctrl1_emotion msgctrl1_emotion NA         1
```

<sup>Created on 2022-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

FYI, you can generate the first line with `test %>% select(msgctrl1_emotion, condition) %>% head(5) %>% dput()` and copy-paste it to your code. Then select your code, copy it, and run reprex::reprex(), and voilà!

I will try to work on this soon.

In the meantime, you can either remove the `filter()` on condition, or remove the `by` clause when condition is filtered.

**Comment by kathrynagnas** [comment]
Hi again,

I was able to get only percentages after including condition without the filter. Thank you, and I will be looking forward to the update :)!

**Comment by DanChaltiel** [comment]
Hi Karthryn,
This bug should now be fixed in the dev version.
You can install it using `devtools::install_github("DanChaltiel/crosstable")`.
This way, you can have the nice header that comes with the `by` clause.
If it still doesn't work, please post the problem here and I will reopen the issue.
