### ISSUE TITLE
Cannot load package

### ISSUE THREAD

**Issue by raecheldavis** [DanChaltiel/crosstable#14]
> install.packages("crosstable")
Installing package into ‘C:/Users/davis/OneDrive/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/crosstable_0.4.1.zip'
Content type 'application/zip' length 539115 bytes (526 KB)
downloaded 526 KB

> library(crosstable)
Error: package or namespace load failed for ‘crosstable’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘xfun’ 0.25 is being loaded, but >= 0.29 is required

**Comment by DanChaltiel** [comment]
Please read the error message:
>`namespace ‘xfun’ 0.25 is being loaded, but >= 0.29 is required`

You need a newer version of `xfun`, try to run `install.packages("xfun")` to update it.
