### ISSUE TITLE
library(crosstable) does not work

### ISSUE THREAD

**Issue by rmkuhn** [DanChaltiel/crosstable#18]
I used the standard r 4,1,0 gui in Windows 10
I got no errors when I installed crosstable today (8/27)

> library(crosstable)
Error: package or namespace load failed for ‘crosstable’:
 object ‘check_dots_empty’ is not exported by 'namespace:rlang'
In addition: Warning messages:
1: package ‘crosstable’ was built under R version 4.1.3 
2: replacing previous import ‘purrr::list_along’ by ‘rlang::list_along’ when loading ‘crosstable’ 
3: replacing previous import ‘purrr::modify’ by ‘rlang::modify’ when loading ‘crosstable’ 
4: replacing previous import ‘purrr::prepend’ by ‘rlang::prepend’ when loading ‘crosstable’

**Comment by DanChaltiel** [comment]
I think you have an older version of rlang.
Could you paste the output of `sessionInfo()`?
Then, could you update rlang and tell me if there are any other messages?
I'm also surprised by the messages you got from `purrr`

**Comment by rmkuhn** [comment]
Enclosed is a copy of sessionInfo.  Should I reinstall rlang and see if it solves the problem?
> library(crosstable)Error: package or namespace load failed for ‘crosstable’: object ‘check_dots_empty’ is not exported by 'namespace:rlang'In addition: Warning messages:1: package ‘crosstable’ was built under R version 4.1.3 2: replacing previous import ‘purrr::list_along’ by ‘rlang::list_along’ when loading ‘crosstable’ 3: replacing previous import ‘purrr::modify’ by ‘rlang::modify’ when loading ‘crosstable’ 4: replacing previous import ‘purrr::prepend’ by ‘rlang::prepend’ when loading ‘crosstable’ > sessionInfo()
R version 4.1.0 (2021-05-18)Platform: x86_64-w64-mingw32/x64 (64-bit)Running under: Windows 10 x64 (build 19043)
Matrix products: default
locale:[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          [5] LC_TIME=English_United States.1252    
attached base packages:[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached): [1] Rcpp_1.0.7        xml2_1.3.2        knitr_1.33        magrittr_2.0.1    uuid_1.1-0        tidyselect_1.1.1  [7] R6_2.5.0          rlang_0.4.11      fansi_0.5.0       stringr_1.4.0     dplyr_1.0.7       tools_4.1.0      [13] checkmate_2.0.0   data.table_1.14.0 xfun_0.32         utf8_1.2.2        cli_3.0.1         htmltools_0.5.1.1[19] systemfonts_1.0.4 ellipsis_0.3.2    digest_0.6.27     tibble_3.1.3      lifecycle_1.0.0   crayon_1.4.1     [25] zip_2.2.0         officer_0.4.3     purrr_0.3.4       base64enc_0.1-3   vctrs_0.3.8       evaluate_0.14    [31] glue_1.4.2        flextable_0.7.3   rmarkdown_2.16    stringi_1.7.3     compiler_4.1.0    pillar_1.6.1     [37] forcats_0.5.1     generics_0.1.0    gdtools_0.2.4     backports_1.2.1   pkgconfig_2.0.3  >

    On Sunday, August 28, 2022 at 02:40:07 PM CDT, Dan Chaltiel ***@***.***> wrote:  
 
 


I think you have an older version of rlang.
Could you paste the output of sessionInfo()?
Then, could you update rlang and tell me if there are any other messages?
I'm also surprised by the messages you got from purrr

**Comment by DanChaltiel** [comment]
Indeed, you need rlang v1.0.0 minimum and you have 0.4.11
That's my bad, as I should have mentioned that in the package so that the dependency updates.
Reinstalling rlang should definitely fix the problem

**Comment by rmkuhn** [comment]
After I reinstalled rlang, your sample run below worked.  You can close my issue.
THANKS


    On Sunday, August 28, 2022 at 02:40:07 PM CDT, Dan Chaltiel ***@***.***> wrote:  
 
 


I think you have an older version of rlang.
Could you paste the output of sessionInfo()?
Then, could you update rlang and tell me if there are any other messages?
I'm also surprised by the messages you got from purrr
