### ISSUE TITLE
Unintuitive showNA="no"

### ISSUE THREAD

**Issue by sda030** [DanChaltiel/crosstable#24]
**Describe the bug**
When setting showNA="no", the user expects that NAs are also omitted from totals. However, they creep in (se column 6 below). This means that a manual summation of n across cells in a column (or row) does not result in the total. Whether or not this is intended, it is very counter-intuitive. Also, NA in the by variable are shown, even though showNA is "no" (see column NA below). 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(crosstable)
x <- data.frame(a=c(1:3, NA), b=c(NA, 4:6))
crosstable(x, cols=a, by=b, total="both", showNA = "no")
#> # A tibble: 4 × 8
#>   .id   label variable `4`         `5`         `6`        `NA`  Total      
#>   <chr> <chr> <chr>    <chr>       <chr>       <chr>      <chr> <chr>      
#> 1 a     a     1        0 (NA%)     0 (NA%)     0 (NA%)    <NA>  1 (33.33%) 
#> 2 a     a     2        1 (100.00%) 0 (0%)      0 (0%)     <NA>  1 (33.33%) 
#> 3 a     a     3        0 (0%)      1 (100.00%) 0 (0%)     <NA>  1 (33.33%) 
#> 4 a     a     Total    1 (33.33%)  1 (33.33%)  1 (33.33%) 1     4 (100.00%)
```

<sup>Created on 2022-10-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23 ucrt)
#>  os       Windows 10 x64 (build 22621)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  nb.utf8
#>  ctype    nb.utf8
#>  tz       Europe/Berlin
#>  date     2022-10-25
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  ! package     * version    date (UTC) lib source
#>    assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.2.1)
#>    backports     1.4.1      2021-12-13 [1] CRAN (R 4.2.0)
#>  P base64enc     0.1-3      2015-07-28 [?] CRAN (R 4.0.3)
#>    checkmate     2.1.0      2022-04-21 [1] CRAN (R 4.2.1)
#>    cli           3.4.1      2022-09-23 [1] CRAN (R 4.2.1)
#>    crosstable  * 0.5.0.9006 2022-10-25 [1] Github (DanChaltiel/crosstable@995c7f6)
#>    data.table    1.14.2     2021-09-27 [1] CRAN (R 4.2.1)
#>    DBI           1.1.3      2022-06-18 [1] CRAN (R 4.2.1)
#>  P digest        0.6.30     2022-10-18 [?] CRAN (R 4.2.1)
#>    dplyr       * 1.0.10     2022-09-01 [1] CRAN (R 4.2.1)
#>    ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.2.1)
#>  P evaluate      0.17       2022-10-07 [?] CRAN (R 4.2.1)
#>    fansi         1.0.3      2022-03-24 [1] CRAN (R 4.2.1)
#>  P fastmap       1.1.0      2021-01-25 [?] CRAN (R 4.0.3)
#>    flextable     0.8.2      2022-09-26 [1] CRAN (R 4.2.1)
#>    forcats       0.5.2      2022-08-19 [1] CRAN (R 4.2.1)
#>  P fs            1.5.2      2021-12-08 [?] CRAN (R 4.1.2)
#>    gdtools       0.2.4      2022-02-14 [1] CRAN (R 4.2.1)
#>    generics      0.1.3      2022-07-05 [1] CRAN (R 4.2.1)
#>  P glue          1.6.2      2022-02-24 [?] CRAN (R 4.1.2)
#>  P highr         0.9        2021-04-16 [?] CRAN (R 4.0.5)
#>  P htmltools     0.5.3      2022-07-18 [?] CRAN (R 4.2.1)
#>  P knitr         1.40       2022-08-24 [?] CRAN (R 4.2.1)
#>    lifecycle     1.0.3      2022-10-07 [1] CRAN (R 4.2.1)
#>  P magrittr      2.0.3      2022-03-30 [?] CRAN (R 4.1.3)
#>    officer       0.4.4      2022-09-09 [1] CRAN (R 4.2.1)
#>    pillar        1.8.1      2022-08-19 [1] CRAN (R 4.2.1)
#>    pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.2.1)
#>    purrr         0.3.5      2022-10-06 [1] CRAN (R 4.2.1)
#>  P R6            2.5.1      2021-08-19 [?] CRAN (R 4.1.1)
#>    Rcpp          1.0.9      2022-07-08 [1] CRAN (R 4.2.1)
#>    reprex        2.0.2      2022-08-17 [1] CRAN (R 4.2.1)
#>  P rlang         1.0.6      2022-09-24 [?] CRAN (R 4.2.1)
#>  P rmarkdown     2.17       2022-10-07 [?] CRAN (R 4.2.1)
#>    rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.2.1)
#>  P sessioninfo   1.2.2      2021-12-06 [?] CRAN (R 4.2.1)
#>  P stringi       1.7.8      2022-07-11 [?] CRAN (R 4.2.1)
#>  P stringr       1.4.1      2022-08-20 [?] CRAN (R 4.2.1)
#>    systemfonts   1.0.4      2022-02-11 [1] CRAN (R 4.2.1)
#>    tibble        3.1.8      2022-07-22 [1] CRAN (R 4.2.1)
#>    tidyr         1.2.1      2022-09-08 [1] CRAN (R 4.2.1)
#>    tidyselect    1.2.0      2022-10-10 [1] CRAN (R 4.2.1)
#>    utf8          1.2.2      2021-07-24 [1] CRAN (R 4.2.1)
#>    uuid          1.1-0      2022-04-19 [1] CRAN (R 4.2.0)
#>    vctrs         0.4.2      2022-09-29 [1] CRAN (R 4.2.1)
#>    withr         2.5.0      2022-03-03 [1] CRAN (R 4.2.1)
#>  P xfun          0.34       2022-10-18 [?] CRAN (R 4.2.1)
#>    xml2          1.3.3      2021-11-30 [1] CRAN (R 4.2.1)
#>  P yaml          2.3.6      2022-10-18 [?] CRAN (R 4.2.1)
#>    zip           2.2.1      2022-09-08 [1] CRAN (R 4.2.1)
#> 
#>  [1] C:/Users/py128/OneDrive - NIFU/Github-R/skolesporringer/renv/library/R-4.2/x86_64-w64-mingw32
#>  [2] C:/Users/py128/AppData/Local/Temp/Rtmpgp6H7Y/renv-system-library
#>  [3] C:/Users/py128/AppData/Local/Programs/R/R-4.2.1/library
#> 
#>  P ── Loaded and on-disk path mismatch.
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by sda030** [comment]
Having perused your code, it seems to me that [`length(x)` should instead be `length(rtn)`, to accompany the smaller table without NA?](https://github.com/DanChaltiel/crosstable/blob/main/R/cross_categorical.R#L78)  Also, is `length()` the appropriate here, or should it not be nrow()? My experience is that length() often does not do what you think..

**Comment by sda030** [comment]
Noticed now another bug in the same example: Percentages for the first row "0 (NA%)"

**Comment by DanChaltiel** [comment]
All of this is indeed the expected behavior and the result of a massive headache-inducing reflection.

In your example, the total-total should be 4, as it is the number of rows of `data`, and it should obviously be 100%.
The total of each `a` level is 1 (regardless of `b`) so it would feel wrong to have 0 here just because there are missing data in `b`.
But indeed, if you hide the NA with `showNA = "no"`, you end up with that mismatch in the totals (3 vs 4).
Same for the proportions, computing them with the NA would yield 1/4=25% which would feel wrong.

In the end, I really dislike this option `showNA = "no"` as I could not find a way to have a clean, yet meaningful output with it. 
Moreover, IMHO, if your dataset has missing values, you definitely should describe them. 

Note that if you really want to, you can use [`n_row_na`](https://github.com/DanChaltiel/crosstable/blob/main/NEWS.md#new-features-1) in `percent_pattern` since version 0.5.

**However, you are totally right that this might be really unintuitive to the user.**

I should put a once-per-session warning when this option is used, something like this:
> `Using showNA = "no" will hide the missing values from the output, but they will still be counted in the proportions. If you want to completely remove them you can either use dplyr::filter(!is.na(x)) or forcats::fct_explicit_na(x) before applying crosstable(), or use p_na in percent_pattern.`

If you have a better idea, or any suggestion for this warning (English is not my first language), I'm very open-minded on the subject 😊

**Comment by DanChaltiel** [comment]
Oh ok, I just saw your first point, the `NA` column should indeed not be there if `showNA = "no"`!

**Comment by sda030** [comment]
Think I'll start with "Moreover, IMHO, if your dataset has missing values, you definitely should describe them.":
We have survey data where question 2:10 is administered to a select few, conditional on responses to question 1. In regular reporting of these, it makes no sense to show a constant NA-percentage (or N) for all these, it just clutters. Nor is it practical to remove all the non-target respondents either, because construction of these tables in the reports are semi-automated. Moreover, the NAs are better addressed elsewhere.

As for "the total-total should be 4, as it is the number of rows of data, and it should obviously be 100%", I do not believe this is consistent with base-R (which I generally consider to be a good "best practice"). 
[`marginSums()`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/marginSums.html) computes the sum of the columns and rows based on the visible cells, rather than ensuring that the total-total (grand total?) equals nrow(data). Same applies to the addmargins()-function in baseR. This is not too surprising, as it takes a table or matrix as input and has no idea of the original data. Also, if you look at more advanced statistical modelling software that also produce bivariate tables, row/col totals and total-total are all based on observed cells (Mplus is an example easily at my hand), likely because all missing values are omitted before tables are constructed (and thus before analyses are done). I tried to check what gtsummary::tbl_summary() uses, but they do not provide totals.
 
I also think I like showNA, because it mirrors baseR in table(). 

P.S. Don't excuse your English, more than good enough.

**Comment by DanChaltiel** [comment]
This NA column has been taken care of, let's focus on those percentages and totals now. 

There might be a way to do what you want with crosstable using a custom `percent_pattern`, as described [here](https://github.com/DanChaltiel/crosstable/blob/main/NEWS.md#new-features-1). 

For instance, please try this code:
```
PATTERN_NA=list(body="Cell: p = {p_cell_na} ({n}/{n_tot_na}) [95%CI {p_cell_na_inf}; {p_cell_na_sup}]
                        Col: p = {p_col_na} ({n}/{n_col_na}) [95%CI: {p_col_na_inf}; {p_col_na_sup}] \nRow:p = {p_row_na} ({n}/{n_row_na}): [95%CI: {p_row_na_inf}; {p_row_na_sup}]",
                total_row="N={n} \nRow:p = {p_row_na} ({n}/{n_row_na}) [95%CI: {p_row_na_inf}; {p_row_na_sup}]",
                total_col="N={n} \nCol: p = {p_col_na} ({n}/{n_col_na}) [95%CI: {p_col_na_inf}; {p_col_na_sup}]",
                total_all="N={n} (100%) [95%CI: {p_col_na_inf}; {p_col_na_sup}]")
x <- data.frame(a=c(1:3, NA), b=c(NA, 4:6), c=c(1,NA,NA,4))
crosstable(x, cols=a, by=b, total="both", showNA = "no", percent_pattern=PATTERN_NA) %>% af()
```
Is there anything that would seem relevant to you here?
On the contrary, are there numbers that you feel are irrelevant?
(I'd admit that this code has been written without much love, so there might be wrong numbers here and there. Any feedback will be appreciated.)

That being said, I still would not consider it good practice to remove NA entirely. In your example, having a separated crosstable, filtered on the ones the questionnaire has been administered to, would enable you to describe how much missing data you have for these people. Keeping them in the whole population gives an overestimation of missing data, but plainly removing them seems pretty wrong to me.

**Comment by sda030** [comment]
Good that the NA-col is fixed, as well as the other PRs. 
No, the suggested table does not really address the core issue in any way, because the grand total is 4, whereas the margins (total_row and total_col) each sum to 3. Also, each of the total_col for the first row and the total_row for the last column says N=1 even though there are no counts in the cells for their respective row/column. It simply does not add up. I tried showing the simplified table below to colleagues and they pointed out the inconsistency. 

Also tested out the janitor and gtsummary packages, which are consistent regarding showing/hiding NAs in row/col/grand-totals:

``` r
library(janitor)
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test
x <- data.frame(a=c(1:3, NA), b=c(NA, 4:6))
tabyl(dat = x, a, b, show_na = FALSE) %>% 
  adorn_totals(where = c("row", "col"))
#>      a 4 5 Total
#>      2 1 0     1
#>      3 0 1     1
#>  Total 1 1     2

tabyl(dat = x, a, b, show_na = TRUE) %>% 
  adorn_totals(where = c("row", "col"))
#>      a 4 5 6 NA_ Total
#>      1 0 0 0   1     1
#>      2 1 0 0   0     1
#>      3 0 1 0   0     1
#>   <NA> 0 0 1   0     1
#>  Total 1 1 1   1     4

## Same with gtsummary
library(gtsummary)
x <- data.frame(a=c(1:3, NA), b=c(NA, 4:6))
tbl_cross(x, row = a, col = b, 
          margin = c("row", "col"), missing = "no") |>
  as_tibble()
#> FALSE observations with missing data have been removed.
#> # A tibble: 5 × 5
#>   ``    `4`   `5`   `6`   Total
#>   <chr> <chr> <chr> <chr> <chr>
#> 1 a     <NA>  <NA>  <NA>  <NA> 
#> 2 1     0     0     0     0    
#> 3 2     1     0     0     1    
#> 4 3     0     1     0     1    
#> 5 Total 1     1     0     2

tbl_cross(x, row = a, col = b, digits = 0, 
          margin = c("row", "col"), missing = "ifany") |>
  as_tibble() # Slightly buggy when converting to a tibble. a is just a label, not a real row.
#> # A tibble: 6 × 6
#>   ``      `4`   `5`   `6`   Unknown Total
#>   <chr>   <chr> <chr> <chr> <chr>   <chr>
#> 1 a       <NA>  <NA>  <NA>  <NA>    <NA> 
#> 2 1       0     0     0     1       1    
#> 3 2       1     0     0     0       1    
#> 4 3       0     1     0     0       1    
#> 5 Unknown 0     0     1     0       1    
#> 6 Total   1     1     1     1       4
```

<sup>Created on 2022-11-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DanChaltiel** [comment]
Hmmm, you are right, I should probably align with `janitor` and `gtsummary` then.

**Comment by sda030** [comment]
Thanks!
P. S. You might want to consider highlighting on the readme that crosstable is faster than gtsummary for exporting to flextable, though I havent thoroughly benchmarked them.

**Comment by DanChaltiel** [comment]
Thanks for the info!
Actually, I have always coded crosstable for my own use and I have absolutely no idea how people use my package so if your whole automation code is shareable, I'd be very interested!

**Comment by DanChaltiel** [comment]
Hi,
I think this is done with the latest commits.
I think I should rename `showNA` to `useNA` though, as it is not only a matter of showing anymore.

I'll commit to CRAN before the end of the year :-)

**Comment by sda030** [comment]
Agree, useNA would be even better for newbie R users.
Looking forward to cran release! Will use it in a course.
