### ISSUE TITLE
Store N as attribute

### ISSUE THREAD

**Issue by sda030** [DanChaltiel/crosstable#26]
For downstream wrapper functions (i.e. table notes, captions, etc) it would be great if N, meaning nrow(data) was stored as an attribute as part of the crosstable class. Should be quite easy to implement, and not resulting in risky behaviour? Currently impossible to recreate N by summing up the value-column, because the table might only consist of e.g. percentages.

**Comment by DanChaltiel** [comment]
Yes, this would be very easy to implement, in the next release (in 2022 I hope, if I manage to free up some time).

I never had to use that myself but I like the idea to save information in attributes. The more the better, so feel free to ask!
