### ISSUE TITLE
Replace forcats::fct_explicit_na()  with forcats::fct_na_value_to_level()

### ISSUE THREAD

**Issue by sda030** [DanChaltiel/crosstable#29]
With the latest forcats 1.0, there is a lifecycle note that forcats::fct_explicit_na() has been deprecated in favour of the new forcats::fct_na_value_to_level(). 
No big deal yet, works fine for now.

**Comment by DanChaltiel** [comment]
That warning started to get annoying! 😈
Fixed in 26dab4a34c39a199f8660cd7a4fdb50ea3cf86aa
