### ISSUE TITLE
Optimizing by optional getTableCI()

### ISSUE THREAD

**Issue by sda030** [DanChaltiel/crosstable#34]
Hi Dan, 
While profiling my own downstream package I noticed that crosstable() spends significant amount of time obtaining getTableCI() even if I have not requested it. It is about 300 ms* for the latter (out of a total of 600 ms). Could we either have simple logical argument for turning it off, or that the parser of the glue-like string checks for this? When creating many tables in a report (+ the inevitable iteration until perfection), those 300 ms make a difference. From perusing your summarize_categorical_single() functions it seems easy to insert such a condition? Also, I had a look at getTableCI() and across_unpack() but could not spot any obvious improvements there - I guess the bottleneck is the actual CI computation.

*Note: My toy dataset contained 4 variables and 100 rows. When using the mtcars2 the timings are halved, but still getTableCI() takes about half the time.
`
crosstable::mtcars2 |>
    crosstable::crosstable(cols = tidyselect::matches("vs|am"), 
                           percent_pattern = "{n}", showNA = "ifany", label = TRUE)`

![image](https://user-images.githubusercontent.com/13221371/226349868-63762f9a-0986-4a84-b125-563fe5446026.png)

**Comment by DanChaltiel** [comment]
Hi Stefan, 

This should be fixed now, could you try and tell me?
