### ISSUE TITLE
use of t-tests or rank-sum tests

### ISSUE THREAD

**Issue by linem7** [DanChaltiel/crosstable#35]
Hi Dan,
I am using the crosstable() function to perform some analyses on my data. Specifically, I am using the following code: 

`crosstable(mtcars2, cols = c(disp, qsec), by = am, test = T) %>% as_flextable()`

However, I noticed that the crosstable() function uses a Wilcoxon rank sum test for the disp variable and a t-test for the qsec variable, when comparing the means between the two levels of the am variable. I would like to modify the function to use t-tests for both variables, to ensure consistency across the analyses.

Is it possible to modify the crosstable() function to achieve this? If so, could you please provide some guidance on how to do it?
Thank you very much for your help!

**Comment by DanChaltiel** [comment]
Hi Lin, 

This is normal behavior, as different tests should be performed depending on some conditions.

You can see the exact algorithm at https://github.com/DanChaltiel/crosstable/blob/main/R/test.R#L134.
This algorithm is obviously arguable and I didn't put much work on it (it is actually a remnant of `[biostat2](https://github.com/eusebe/biostat2)`, the package crosstable is from).

In your example, `disp` has a statistically non-normal distribution (as seen in `shapiro.test(mtcars2$disp)` or `car::densityPlot(mtcars2$disp)`) so the Wilcoxon test is probably a better solution than the t-test.

If you really want to perform a standard t-test regardless of the conditions, you could write something like this:

```r
my_test_summarize = function(x, g){
  test = t.test(x ~ g)
  # list(p.value=test$p.value, method=test$method)
  list(p.value=test$p.value, method="Always a t-test")
}

test_args = crosstable_test_args(test_summarize=my_test_summarize)

crosstable(mtcars2, cols = c(disp, qsec), by = am, test=TRUE, test_args=test_args) %>% as_flextable()
```
![image](https://user-images.githubusercontent.com/15105152/227766614-44ef5421-16c5-480f-99a7-064b8b73b764.png)

I don't think it is something you should do though.

**Comment by linem7** [comment]
Your solution worked perfectly and your suggestions were really helpful. I appreciate your time and effort in helping me out. Thanks again!
