### ISSUE TITLE
Cannot activate library(crosstable)

### ISSUE THREAD

**Issue by DanChartrand** [DanChaltiel/crosstable#37]
**Describe the bug**
Cannot activate library(crosstable) version 6

**Reproducible example**
library(crosstable) 
Avis : le package ‘crosstable’ a été compilé avec la version R 4.2.3 Registered S3 method overwritten by 'data.table':   method           from   print.data.table      Error: le chargement du package ou de l'espace de noms a échoué pour ‘crosstable’ : l'objet ‘fct_na_value_to_level’ n'est pas exporté par 'namespace:forcats'
--
 
> | >
>

</body>
</html>

**<summary>Session info</summary>**
<details>
``` r
 #Paste here the output of `sessionInfo()` here
```
</details>

**Comment by DanChaltiel** [comment]
Indeed, you need version 1.0.0 of forcats for the new version of crosstable to work.
I enforced this in the DESCRIPTION so that should be automatically done in the future.
Just update your forcats package ;-)
