### ISSUE TITLE
it can not be installed

### ISSUE THREAD

**Issue by dingying85** [DanChaltiel/crosstable#39]
when I type the following
devtools::install_github("DanChaltiel/crosstable", build_vignettes=TRUE)

It kept giving the following error messages:
** using staged installation
   ** R
   Error in parse(outFile) :
     /tmp/RtmpDgOkKg/Rbuild22af522f5a7/crosstable/R/utils.R:575:46: unexpected '>'
   574: ansi_align_by = function(text, pattern){
   575:   pos = gregexpr(pattern, ansi_strip(text)) |>
                                                     ^
   ERROR: unable to collate and parse R files for package ‘crosstable’

**Comment by DanChaltiel** [comment]
Ooops, I indeed left a base R pipe in my code!

https://github.com/DanChaltiel/crosstable/blob/31162a3d42e0c1707153c078c2e0c64b2edd6aa1/R/utils.R#L575

You might need to install R>4.1 to be able to run it.
I'll correct it asap to keep the backward compatibility.
