### ISSUE TITLE
wrong information in the documentation (again)

### ISSUE THREAD

**Issue by davidgohel** [DanChaltiel/crosstable#58]
https://danchaltiel.github.io/crosstable/articles/crosstable-report.html#post-production-for-tablefigure-legends

> Depending on your version of [officer](https://ardata-fr.github.io/officeverse/), Word will ask you to update the fields

What version of 'officer' automatically updates fields for users? I'm not sure I understand what you mean about 'officer', but it seems badly adapted to users and lacking in clarity. As you pretend to document officer based on your experience of autocompleting, maybe you should warn your reader you don't read the documentation ? https://github.com/davidgohel/flextable/pull/620#issuecomment-2028704187

> Be aware that you unfortunately cannot reference a bookmark more than once using this method. Writing: body_add_normal("Table \\@ref(iris_col1) is about flowers. I like this Table \\@ref(iris_col1).") will prevent all the numbering from applying.

Is that a limit of crosstable? If your sentence implies it is a limit of 'officer', please correct and explain this is about your implementation because officer has not this limitation

**Comment by DanChaltiel** [comment]
Same as #57, this vignette is just very outdated.

Actually, I happened to notice this one on my own and was very surprised it worked. 
I think this comes from the abandoning of `slip_in_*()` but this is so old it is not relevant anymore.

Closing here in favor of #57.
